# Generated by Django 5.0.4 on 2024-05-10 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.CreateModel(
            name='Lense',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_desc', models.TextField()),
                ('p_quantity', models.PositiveIntegerField()),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('p_image', models.ImageField(upload_to='uploads')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='p_app.category')),
            ],
            options={
                'db_table': 'p_app',
            },
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p_app.lense'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(to='p_app.lense'),
        ),
        migrations.DeleteModel(
            name='Perfume',
        ),
    ]
