# Generated by Django 5.0.4 on 2024-05-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_app', '0002_userdetails_email_lense_alter_cartproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
